server:
  port: 8080

vmcServicesAddr:
  UserManager: "http://localhost:8001"
  VerificationManager: "http://localhost:8002"
  TransactionManager: "http://localhost:8003"

spring:
  redis:
    host: localhost
    port: 6379

# You should inject secret
token:
  secret: ahfmrpTek


logging:
  file:
    name: "user-manager.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB