vmcServicesAddr:
  UserManager: "http://localhost:8001"
  VerificationManager: "http://localhost:8002"
  TransactionManager: "http://localhost:8003"

server:
  port: 8000
spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    include: oauth
foo: bar_default