server:
  port: 8080

spring:
  redis:
    host: redis
    port: 6379

service:
  vmcServicesAddr:
    UserManager: "http://user-manager:8080"
    VerificationManager: "http://verification-manager:8080"
    TransactionManager: "http://transaction-manager:8080"

  allowedOrigin: "http://vmc-front-prd.s3-website.ap-northeast-2.amazonaws.com"

  # You should inject secret
  token:
    secret: ahfmrpTek


logging:
  file:
    name: "/log/apigateway.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB
      total-size-cap: 100MB