server:
  port: 8080

vmcServicesAddr:
  UserManager: "http://user-manager:8080"
  VerificationManager: "http://verification-manager:8080"
  TransactionManager: "http://transaction-manager:8080"

spring:
  redis:
    host: redis
    port: 6379

# You should inject secret
token:
  secret: ahfmrpTek
