server:
  port: 8000

spring:
  redis:
    host: localhost
    port: 6379

service:
  vmcServicesAddr:
    UserManager: "http://localhost:8001"
    VerificationManager: "http://localhost:8002"
    TransactionManager: "http://localhost:8003"

  allowedOrigin: "http://localhost:3000"

  # You should inject secret
  token:
    secret: ahfmrpTek
