server:
  port: 8000
  ssl:
    enabled: true
    key-alias: vmc_key_store
    key-store-password: 123456
    key-store: classpath:vmc_key_store.p12
    key-store-type: PKCS12

vmcServicesAddr:
  UserManager: "http://localhost:8001"
  VerificationManager: "http://localhost:8002"
  TransactionManager: "http://localhost:8003"

spring:
  redis:
    host: localhost
    port: 6379



# You should inject secret
token:
  secret: ahfmrpTek