server:
  port: 8080
  ssl:
    enabled: true
    key-alias: vmc_key_store
    key-store-password: 123456
    key-store: classpath:vmc_key_store.p12
    key-store-type: PKCS12

vmcServicesAddr:
  UserManager: "http://user-manager:8080"
  VerificationManager: "http://verification-manager:8080"
  TransactionManager: "http://transaction-manager:8080"

spring:
  redis:
    host: redis
    port: 6379

# You should inject secret
token:
  secret: ahfmrpTek